language: php

branches:
  only:
    - main

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - LOG_DIR=tests/logs
    - CODECOV_TOKEN=08d85771-8ca8-4247-be7d-dc66c6742a5a

before_install:

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer clear
  - composer install --no-scripts -vvv
  - curl --data-binary @codecov.yml https://codecov.io/validate

jobs:
  include:
    - stage: Test
      script:
        - mkdir -p tests/output
        - XDEBUG_MODE=coverage phpunit --configuration phpunit.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f tests/output/clover.xml