name: Package Test

on:
  schedule:
    - cron:  '1/13 4-10 * * *'
jobs:
   package-test:
    name: "Composer package install test"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - '8.0'
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: Install dependencies
        run: composer require ouxsoft/luckbydice
